package Interface;

import Interface.Menul;
import javax.swing.JOptionPane;

/**
 *
 * @author epic4
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1Login = new javax.swing.JLabel();
        jTextField1Usuario = new javax.swing.JTextField();
        jLabel2Usuario = new javax.swing.JLabel();
        jLabel3Senha = new javax.swing.JLabel();
        jPasswordField1Senha = new javax.swing.JPasswordField();
        jButton1Acessar = new javax.swing.JButton();
        jButton2Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1Login.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1Login.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1Login.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1Login.setText("Login");

        jTextField1Usuario.setBackground(new java.awt.Color(153, 153, 153));
        jTextField1Usuario.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2Usuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2Usuario.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2Usuario.setText("Usuario");

        jLabel3Senha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3Senha.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3Senha.setText("Senha");

        jPasswordField1Senha.setBackground(new java.awt.Color(153, 153, 153));
        jPasswordField1Senha.setForeground(new java.awt.Color(0, 0, 0));

        jButton1Acessar.setBackground(new java.awt.Color(153, 153, 153));
        jButton1Acessar.setForeground(new java.awt.Color(0, 0, 0));
        jButton1Acessar.setText("Acessar");
        jButton1Acessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AcessarActionPerformed(evt);
            }
        });

        jButton2Sair.setBackground(new java.awt.Color(153, 153, 153));
        jButton2Sair.setForeground(new java.awt.Color(0, 0, 0));
        jButton2Sair.setText("Sair");
        jButton2Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2Usuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3Senha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordField1Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1Acessar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2Sair)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1Login)
                        .addGap(163, 163, 163))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1Login)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2Usuario))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3Senha)
                    .addComponent(jPasswordField1Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Acessar)
                    .addComponent(jButton2Sair))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(427, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1AcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AcessarActionPerformed
     Acessar();
    }//GEN-LAST:event_jButton1AcessarActionPerformed

    private void jButton2SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2SairActionPerformed
      Fechar();
    }//GEN-LAST:event_jButton2SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Acessar;
    private javax.swing.JButton jButton2Sair;
    private javax.swing.JLabel jLabel1Login;
    private javax.swing.JLabel jLabel2Usuario;
    private javax.swing.JLabel jLabel3Senha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1Senha;
    private javax.swing.JTextField jTextField1Usuario;
    // End of variables declaration//GEN-END:variables

    private void Acessar(){
        if (jTextField1Usuario.getText().equals("admin") //se campo usuario e senha receber admin admin faça
        &&jPasswordField1Senha.getText().equals("admin")){
        Menul tela = new Menul();//objeto menul
        tela.setVisible(true);//tornar Menul visivel e fechar
        dispose();
        } else {
        JOptionPane.showMessageDialog(rootPane, "Senha ou Usuario Invalidos!"); }
    }

    private void Fechar(){
        System.exit(0);//fechar
    }
    
}
