/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Conexao.ProdutosDAO;
import Controle.Entrada;
import Controle.Produtos;
import Controle.Saida;
import Controle.View;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author epic4
 */
public class MenuProdutos extends javax.swing.JFrame {

    /**
     * Creates new form MenuVendas
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Principal = new javax.swing.JPanel();
        jLabel1Menu = new javax.swing.JLabel();
        jLabel1Produtos = new javax.swing.JLabel();
        jLabel5Produtoss = new javax.swing.JLabel();
        jLabel8TotalC = new javax.swing.JLabel();
        jLabel9TotalCaptal = new javax.swing.JLabel();
        jLabel10TotalL = new javax.swing.JLabel();
        jLabel11TotalLucro = new javax.swing.JLabel();
        jPanel1Principal1 = new javax.swing.JPanel();
        jLabel1Menu1 = new javax.swing.JLabel();
        jLabel1Produtos1 = new javax.swing.JLabel();
        jLabel5Produtoss1 = new javax.swing.JLabel();
        jLabel10TotalL1 = new javax.swing.JLabel();
        jLabel11TotalLucro1 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        jLabel10TotalL2 = new javax.swing.JLabel();
        jLabel11TotalLucro2 = new javax.swing.JLabel();
        cbxFornecedor = new javax.swing.JComboBox<>();
        jBExcluir = new javax.swing.JButton();
        jLabel5Produtoss2 = new javax.swing.JLabel();
        jLabel1Produtos2 = new javax.swing.JLabel();
        txtCdg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProdutos = new javax.swing.JTable();
        jBAtualizar = new javax.swing.JButton();
        jBCadastrar2 = new javax.swing.JButton();
        jBAlterar1 = new javax.swing.JButton();
        jLabel10TotalL3 = new javax.swing.JLabel();
        jLabel11TotalLucro3 = new javax.swing.JLabel();
        txtPrecoV = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1Opcoes = new javax.swing.JMenu();
        jMCadastrarFornecedor = new javax.swing.JMenuItem();
        jMCadastrarProdutos = new javax.swing.JMenuItem();
        jMStatus = new javax.swing.JMenuItem();
        jMSaida = new javax.swing.JMenuItem();
        jMenu = new javax.swing.JMenuItem();
        jMLogar = new javax.swing.JMenuItem();
        jMenu2Config = new javax.swing.JMenu();
        jMenuItem4Ferramentas = new javax.swing.JMenuItem();
        jMenu3Sair = new javax.swing.JMenu();
        jMenuItem1Sair = new javax.swing.JMenuItem();

        jPanel1Principal.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1Principal.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1Principal.setLayout(null);

        jLabel1Menu.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1Menu.setText("Menu");
        jPanel1Principal.add(jLabel1Menu);
        jLabel1Menu.setBounds(380, 10, 130, 40);

        jLabel1Produtos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1Produtos.setText("Produtos");
        jPanel1Principal.add(jLabel1Produtos);
        jLabel1Produtos.setBounds(50, 90, 80, 30);

        jLabel5Produtoss.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5Produtoss.setText("Em Estoque");
        jPanel1Principal.add(jLabel5Produtoss);
        jLabel5Produtoss.setBounds(50, 110, 80, 19);

        jLabel8TotalC.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8TotalC.setText("Total");
        jPanel1Principal.add(jLabel8TotalC);
        jLabel8TotalC.setBounds(50, 150, 80, 30);

        jLabel9TotalCaptal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9TotalCaptal.setText("Captal Investido");
        jPanel1Principal.add(jLabel9TotalCaptal);
        jLabel9TotalCaptal.setBounds(50, 170, 110, 19);

        jLabel10TotalL.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10TotalL.setText("Total");
        jPanel1Principal.add(jLabel10TotalL);
        jLabel10TotalL.setBounds(50, 210, 80, 30);

        jLabel11TotalLucro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11TotalLucro.setText("De Lucro");
        jPanel1Principal.add(jLabel11TotalLucro);
        jLabel11TotalLucro.setBounds(50, 230, 60, 19);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(880, 674));
        getContentPane().setLayout(null);

        jPanel1Principal1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1Principal1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1Principal1.setLayout(null);

        jLabel1Menu1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1Menu1.setText("Cadastrar Produtos");
        jPanel1Principal1.add(jLabel1Menu1);
        jLabel1Menu1.setBounds(210, 20, 460, 40);

        jLabel1Produtos1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1Produtos1.setText("Descrição");
        jPanel1Principal1.add(jLabel1Produtos1);
        jLabel1Produtos1.setBounds(10, 80, 90, 30);

        jLabel5Produtoss1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5Produtoss1.setText("Do Produto");
        jPanel1Principal1.add(jLabel5Produtoss1);
        jLabel5Produtoss1.setBounds(10, 100, 80, 19);

        jLabel10TotalL1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10TotalL1.setText("Fornecedor");
        jPanel1Principal1.add(jLabel10TotalL1);
        jLabel10TotalL1.setBounds(20, 140, 110, 30);

        jLabel11TotalLucro1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11TotalLucro1.setText("Do Produto");
        jPanel1Principal1.add(jLabel11TotalLucro1);
        jLabel11TotalLucro1.setBounds(20, 160, 80, 19);

        txtPreco.setBackground(new java.awt.Color(153, 153, 153));
        txtPreco.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1Principal1.add(txtPreco);
        txtPreco.setBounds(450, 90, 140, 30);

        txtDesc.setBackground(new java.awt.Color(153, 153, 153));
        txtDesc.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1Principal1.add(txtDesc);
        txtDesc.setBounds(100, 90, 210, 30);

        jLabel10TotalL2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10TotalL2.setText("Preço");
        jPanel1Principal1.add(jLabel10TotalL2);
        jLabel10TotalL2.setBounds(320, 80, 60, 30);

        jLabel11TotalLucro2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11TotalLucro2.setText("Unitario de Compra");
        jPanel1Principal1.add(jLabel11TotalLucro2);
        jLabel11TotalLucro2.setBounds(320, 100, 130, 19);

        cbxFornecedor.setBackground(new java.awt.Color(153, 153, 153));
        cbxFornecedor.setEditable(true);
        cbxFornecedor.setForeground(new java.awt.Color(0, 0, 0));
        cbxFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jPanel1Principal1.add(cbxFornecedor);
        cbxFornecedor.setBounds(130, 150, 160, 30);

        jBExcluir.setBackground(new java.awt.Color(153, 153, 153));
        jBExcluir.setForeground(new java.awt.Color(0, 0, 0));
        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });
        jPanel1Principal1.add(jBExcluir);
        jBExcluir.setBounds(700, 150, 70, 30);

        jLabel5Produtoss2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5Produtoss2.setText("Do Produto");
        jPanel1Principal1.add(jLabel5Produtoss2);
        jLabel5Produtoss2.setBounds(300, 160, 80, 19);

        jLabel1Produtos2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1Produtos2.setText("Codigor");
        jPanel1Principal1.add(jLabel1Produtos2);
        jLabel1Produtos2.setBounds(300, 140, 90, 30);

        txtCdg.setEditable(false);
        txtCdg.setBackground(new java.awt.Color(153, 153, 153));
        txtCdg.setForeground(new java.awt.Color(0, 0, 0));
        txtCdg.setEnabled(false);
        jPanel1Principal1.add(txtCdg);
        txtCdg.setBounds(380, 150, 120, 30);

        jTProdutos.setBackground(new java.awt.Color(153, 153, 153));
        jTProdutos.setForeground(new java.awt.Color(0, 0, 0));
        jTProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Quantidade", "Preço", "Preço Unitario de Venda", "Fornecedor", "Codigo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTProdutos);

        jPanel1Principal1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 200, 880, 470);

        jBAtualizar.setBackground(new java.awt.Color(153, 153, 153));
        jBAtualizar.setForeground(new java.awt.Color(0, 0, 0));
        jBAtualizar.setText("Atualizar");
        jBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarActionPerformed(evt);
            }
        });
        jPanel1Principal1.add(jBAtualizar);
        jBAtualizar.setBounds(780, 150, 80, 30);

        jBCadastrar2.setBackground(new java.awt.Color(153, 153, 153));
        jBCadastrar2.setForeground(new java.awt.Color(0, 0, 0));
        jBCadastrar2.setText("Cadastrar");
        jBCadastrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrar2ActionPerformed(evt);
            }
        });
        jPanel1Principal1.add(jBCadastrar2);
        jBCadastrar2.setBounds(510, 150, 87, 30);

        jBAlterar1.setBackground(new java.awt.Color(153, 153, 153));
        jBAlterar1.setForeground(new java.awt.Color(0, 0, 0));
        jBAlterar1.setText("Alterar");
        jBAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterar1ActionPerformed(evt);
            }
        });
        jPanel1Principal1.add(jBAlterar1);
        jBAlterar1.setBounds(610, 150, 80, 30);

        jLabel10TotalL3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10TotalL3.setText("Preço");
        jPanel1Principal1.add(jLabel10TotalL3);
        jLabel10TotalL3.setBounds(600, 80, 60, 30);

        jLabel11TotalLucro3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11TotalLucro3.setText("Unitario de Venda");
        jPanel1Principal1.add(jLabel11TotalLucro3);
        jLabel11TotalLucro3.setBounds(600, 100, 120, 20);

        txtPrecoV.setBackground(new java.awt.Color(153, 153, 153));
        txtPrecoV.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoVActionPerformed(evt);
            }
        });
        jPanel1Principal1.add(txtPrecoV);
        txtPrecoV.setBounds(720, 90, 140, 30);

        getContentPane().add(jPanel1Principal1);
        jPanel1Principal1.setBounds(0, 0, 880, 674);

        jMenuBar2.setForeground(new java.awt.Color(153, 153, 153));

        jMenu1Opcoes.setText("Opções");

        jMCadastrarFornecedor.setText("Cadastrar Fornecedor");
        jMCadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarFornecedorActionPerformed(evt);
            }
        });
        jMenu1Opcoes.add(jMCadastrarFornecedor);

        jMCadastrarProdutos.setText("Cadastrar Produtos");
        jMCadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarProdutosActionPerformed(evt);
            }
        });
        jMenu1Opcoes.add(jMCadastrarProdutos);

        jMStatus.setText("Entrada de Produtos");
        jMStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMStatusActionPerformed(evt);
            }
        });
        jMenu1Opcoes.add(jMStatus);

        jMSaida.setText("Saida de  Produtos");
        jMSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSaidaActionPerformed(evt);
            }
        });
        jMenu1Opcoes.add(jMSaida);

        jMenu.setText("Menu");
        jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActionPerformed(evt);
            }
        });
        jMenu1Opcoes.add(jMenu);

        jMLogar.setText("Logar");
        jMLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMLogarActionPerformed(evt);
            }
        });
        jMenu1Opcoes.add(jMLogar);

        jMenuBar2.add(jMenu1Opcoes);

        jMenu2Config.setText("Configurações");

        jMenuItem4Ferramentas.setText("Ferramentas");
        jMenu2Config.add(jMenuItem4Ferramentas);

        jMenuBar2.add(jMenu2Config);

        jMenu3Sair.setText("Sair");

        jMenuItem1Sair.setText("Sair");
        jMenu3Sair.add(jMenuItem1Sair);

        jMenuBar2.add(jMenu3Sair);

        setJMenuBar(jMenuBar2);

        setSize(new java.awt.Dimension(896, 733));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public MenuProdutos() {
        initComponents();
        listarProdutos();
        comboBoxFornecedores();

        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        jTProdutos.setRowSorter(new TableRowSorter(modelo));
    }

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        ExcluirProdutos();
        LimparCampos();
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed
        AtualizarProduto();
    }//GEN-LAST:event_jBAtualizarActionPerformed

    private void jBCadastrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrar2ActionPerformed
        CadastrarProduto();
        listarProdutos();
        LimparCampos();
    }//GEN-LAST:event_jBCadastrar2ActionPerformed

    private void jTProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProdutosMouseClicked
        // TODO add your handling code here
        CarregarCampos();
    }//GEN-LAST:event_jTProdutosMouseClicked

    private void jBAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterar1ActionPerformed
        // TODO add your handling code here:
        AlterarProduto();
        LimparCampos();
    }//GEN-LAST:event_jBAlterar1ActionPerformed

    private void jMCadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarFornecedorActionPerformed
        View objtview = new View();
        objtview.MenuFornecedor();
        dispose();
    }//GEN-LAST:event_jMCadastrarFornecedorActionPerformed

    private void jMStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMStatusActionPerformed
        View objtview = new View();
        objtview.MenuEntrada();
        dispose();
    }//GEN-LAST:event_jMStatusActionPerformed

    private void jMSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSaidaActionPerformed
        View objtview = new View();
        objtview.MenuSaida();
        dispose();
    }//GEN-LAST:event_jMSaidaActionPerformed

    private void jMCadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarProdutosActionPerformed
        View objtview = new View();
        objtview.MenuProdutos();
        dispose();
    }//GEN-LAST:event_jMCadastrarProdutosActionPerformed

    private void jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActionPerformed
        View objtview = new View();
        objtview.Menu();
        dispose();
    }//GEN-LAST:event_jMenuActionPerformed

    private void jMLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMLogarActionPerformed
        View objtview = new View();
        objtview.MenuLogin();
        dispose();
    }//GEN-LAST:event_jMLogarActionPerformed

    private void txtPrecoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxFornecedor;
    private javax.swing.JButton jBAlterar1;
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBCadastrar2;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JLabel jLabel10TotalL;
    private javax.swing.JLabel jLabel10TotalL1;
    private javax.swing.JLabel jLabel10TotalL2;
    private javax.swing.JLabel jLabel10TotalL3;
    private javax.swing.JLabel jLabel11TotalLucro;
    private javax.swing.JLabel jLabel11TotalLucro1;
    private javax.swing.JLabel jLabel11TotalLucro2;
    private javax.swing.JLabel jLabel11TotalLucro3;
    private javax.swing.JLabel jLabel1Menu;
    private javax.swing.JLabel jLabel1Menu1;
    private javax.swing.JLabel jLabel1Produtos;
    private javax.swing.JLabel jLabel1Produtos1;
    private javax.swing.JLabel jLabel1Produtos2;
    private javax.swing.JLabel jLabel5Produtoss;
    private javax.swing.JLabel jLabel5Produtoss1;
    private javax.swing.JLabel jLabel5Produtoss2;
    private javax.swing.JLabel jLabel8TotalC;
    private javax.swing.JLabel jLabel9TotalCaptal;
    private javax.swing.JMenuItem jMCadastrarFornecedor;
    private javax.swing.JMenuItem jMCadastrarProdutos;
    private javax.swing.JMenuItem jMLogar;
    private javax.swing.JMenuItem jMSaida;
    private javax.swing.JMenuItem jMStatus;
    private javax.swing.JMenuItem jMenu;
    private javax.swing.JMenu jMenu1Opcoes;
    private javax.swing.JMenu jMenu2Config;
    private javax.swing.JMenu jMenu3Sair;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1Sair;
    private javax.swing.JMenuItem jMenuItem4Ferramentas;
    private javax.swing.JPanel jPanel1Principal;
    private javax.swing.JPanel jPanel1Principal1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTProdutos;
    private javax.swing.JTextField txtCdg;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtPrecoV;
    // End of variables declaration//GEN-END:variables

    
    private void AlterarProduto() {
        
        Produtos objprodutos = new Produtos();
        ProdutosDAO dao = new ProdutosDAO();

        objprodutos.setDesc(txtDesc.getText());
        objprodutos.setPreco(Double.parseDouble(txtPreco.getText()));
        objprodutos.setPrecoVenda(Double.parseDouble(txtPrecoV.getText()));
        objprodutos.setFornecedor(codigF.get(cbxFornecedor.getSelectedIndex()));
        objprodutos.setCodigo(Integer.parseInt(txtCdg.getText()));
        dao.AlterarProduto(objprodutos);

        AtualizarProduto();
    }

    private void CadastrarProduto() {//metodo de cadastrar
        Produtos objprodutos = new Produtos();
        ProdutosDAO dao = new ProdutosDAO();

        objprodutos.setDesc(txtDesc.getText()); //capta dado digitado e armazena em variavel jogando para o banco de dados
        objprodutos.setPreco(Double.parseDouble(txtPreco.getText()));
        objprodutos.setPrecoVenda(Double.parseDouble(txtPrecoV.getText()));
        objprodutos.setFornecedor(cbxFornecedor.getSelectedIndex());
        dao.cadastroProduto(objprodutos);//executa o metodo com comandos do Db
        
        AtualizarProduto();
    }

    public void AtualizarProduto() {

        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        modelo.setNumRows(0);
        ProdutosDAO pdao = new ProdutosDAO();
        
        for (Controle.Produtos objprodutos : pdao.pesquisarProduto()) {
            
            modelo.addRow(new Object[]{
                objprodutos.getDesc(),
                objprodutos.getQuantAtual(),
                objprodutos.getPreco(),
                objprodutos.getPrecoVenda(),
                objprodutos.getFornecedor(),
                objprodutos.getCodigo(),

            });
        }
        LimparCampos();
    }

    private void ExcluirProdutos() {
        Produtos objprodutos = new Produtos();
        ProdutosDAO dao = new ProdutosDAO();

        objprodutos.setCodigo((int) jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 4));
        dao.ExcluirProduto(objprodutos);

        AtualizarProduto();
    }

    private void listarProdutos() {
        try {
            ProdutosDAO objProdutosdao = new ProdutosDAO();
            
            DefaultTableModel model = (DefaultTableModel) jTProdutos.getModel();//montara a tabela
            model.setNumRows(0);

            ArrayList<Produtos> lista = objProdutosdao.pesquisarProduto();//pegara os dados do db e passara para tabela

            for (int num = 0; num < lista.size(); num++) {//enquanto tiver linhas capte os dados
               model.addRow(new Object[]{
                    lista.get(num).getDesc(),
                    lista.get(num).getQuantAtual(),
                    lista.get(num).getPreco(),
                    lista.get(num).getPrecoVenda(),
                    lista.get(num).getFornecedor(),
                    lista.get(num).getCodigo()
                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ERRO ao Lista de Produtos" + erro);
        }
    }

    Vector<Integer> codigF = new Vector<Integer>();

    public void comboBoxFornecedores() {//carrega id dos fornecedores cadastrados e mostra no combox
        try {
            ProdutosDAO objProdutoDAO = new ProdutosDAO();
            ResultSet rs = objProdutoDAO.listarFornecedor();

            while (rs.next()) {
                codigF.addElement(rs.getInt(1));
                cbxFornecedor.addItem(rs.getString(2));

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ERRO ao Carregar ComboBox de Fornecedores" + erro);
        }
    }

    private void CarregarCampos() {
        //Metodo para selecionar dados e itens da tabela
        txtDesc.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 0).toString());
        txtPreco.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 2).toString());
        txtPrecoV.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 3).toString());
        cbxFornecedor.setSelectedIndex(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 4).hashCode());
        txtCdg.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 5).toString());

    }

    private void LimparCampos(){
        txtDesc.setText("");
        txtPreco.setText("");
        txtPrecoV.setText("");
        txtCdg.setText("");
    }
    
}
