package Interface;

import Conexao.FornecedorDAO;
import Controle.Fornecedor;
import Controle.View;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author epic4
 */
public class MenuFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form MenuVendas
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Principal = new javax.swing.JPanel();
        jLabel1Menu = new javax.swing.JLabel();
        jLabel1Produtos = new javax.swing.JLabel();
        jLabel5Produtoss = new javax.swing.JLabel();
        jLabel8TotalC = new javax.swing.JLabel();
        jLabel9TotalCaptal = new javax.swing.JLabel();
        jLabel10TotalL = new javax.swing.JLabel();
        jLabel11TotalLucro = new javax.swing.JLabel();
        jPanel1Principal1 = new javax.swing.JPanel();
        jLabel1Menu1 = new javax.swing.JLabel();
        jLabel1Produtos1 = new javax.swing.JLabel();
        jLabel5Produtoss1 = new javax.swing.JLabel();
        jLabel8TotalC1 = new javax.swing.JLabel();
        jLabel9TotalCaptal1 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        txtCnpj = new javax.swing.JTextField();
        txtDescForn = new javax.swing.JTextField();
        jLabel10TotalL2 = new javax.swing.JLabel();
        jLabel11TotalLucro2 = new javax.swing.JLabel();
        jBExcluirF = new javax.swing.JButton();
        jLabel5Produtoss2 = new javax.swing.JLabel();
        jLabel1Produtos2 = new javax.swing.JLabel();
        txtCdg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFornecedor = new javax.swing.JTable();
        jBAlterarF = new javax.swing.JButton();
        jBCadastrarF = new javax.swing.JButton();
        jLabel5Produtoss3 = new javax.swing.JLabel();
        jLabel1Produtos3 = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        jBAtualizar = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1Opcoes = new javax.swing.JMenu();
        jMCadastrarFornecedor = new javax.swing.JMenuItem();
        jMCadastrarProdutos = new javax.swing.JMenuItem();
        jMStatus = new javax.swing.JMenuItem();
        jMSaida = new javax.swing.JMenuItem();
        jMenu = new javax.swing.JMenuItem();
        jMLogar = new javax.swing.JMenuItem();
        jMenu2Config = new javax.swing.JMenu();
        jMenuItem4Ferramentas = new javax.swing.JMenuItem();
        jMenu3Sair = new javax.swing.JMenu();
        jMenuItem1Sair = new javax.swing.JMenuItem();

        jPanel1Principal.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1Principal.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1Principal.setLayout(null);

        jLabel1Menu.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1Menu.setText("Menu");
        jPanel1Principal.add(jLabel1Menu);
        jLabel1Menu.setBounds(380, 10, 130, 40);

        jLabel1Produtos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1Produtos.setText("Produtos");
        jPanel1Principal.add(jLabel1Produtos);
        jLabel1Produtos.setBounds(50, 90, 80, 30);

        jLabel5Produtoss.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5Produtoss.setText("Em Estoque");
        jPanel1Principal.add(jLabel5Produtoss);
        jLabel5Produtoss.setBounds(50, 110, 80, 19);

        jLabel8TotalC.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8TotalC.setText("Total");
        jPanel1Principal.add(jLabel8TotalC);
        jLabel8TotalC.setBounds(50, 150, 80, 30);

        jLabel9TotalCaptal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9TotalCaptal.setText("Captal Investido");
        jPanel1Principal.add(jLabel9TotalCaptal);
        jLabel9TotalCaptal.setBounds(50, 170, 110, 19);

        jLabel10TotalL.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10TotalL.setText("Total");
        jPanel1Principal.add(jLabel10TotalL);
        jLabel10TotalL.setBounds(50, 210, 80, 30);

        jLabel11TotalLucro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11TotalLucro.setText("De Lucro");
        jPanel1Principal.add(jLabel11TotalLucro);
        jLabel11TotalLucro.setBounds(50, 230, 60, 19);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(880, 674));
        getContentPane().setLayout(null);

        jPanel1Principal1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1Principal1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1Principal1.setLayout(null);

        jLabel1Menu1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1Menu1.setText("Fornecedores");
        jPanel1Principal1.add(jLabel1Menu1);
        jLabel1Menu1.setBounds(280, 20, 320, 40);

        jLabel1Produtos1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1Produtos1.setText("Descrição");
        jPanel1Principal1.add(jLabel1Produtos1);
        jLabel1Produtos1.setBounds(20, 70, 90, 30);

        jLabel5Produtoss1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5Produtoss1.setText("Do Fornecedor");
        jPanel1Principal1.add(jLabel5Produtoss1);
        jLabel5Produtoss1.setBounds(20, 90, 96, 19);

        jLabel8TotalC1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8TotalC1.setText("Cnpj");
        jPanel1Principal1.add(jLabel8TotalC1);
        jLabel8TotalC1.setBounds(340, 70, 100, 30);

        jLabel9TotalCaptal1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9TotalCaptal1.setText("Do Fornecedor");
        jPanel1Principal1.add(jLabel9TotalCaptal1);
        jLabel9TotalCaptal1.setBounds(340, 90, 100, 19);

        txtTel.setBackground(new java.awt.Color(153, 153, 153));
        txtTel.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1Principal1.add(txtTel);
        txtTel.setBounds(680, 80, 180, 24);

        txtCnpj.setBackground(new java.awt.Color(153, 153, 153));
        txtCnpj.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1Principal1.add(txtCnpj);
        txtCnpj.setBounds(450, 80, 140, 24);

        txtDescForn.setBackground(new java.awt.Color(153, 153, 153));
        txtDescForn.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1Principal1.add(txtDescForn);
        txtDescForn.setBounds(120, 80, 210, 30);

        jLabel10TotalL2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10TotalL2.setText("Tel");
        jPanel1Principal1.add(jLabel10TotalL2);
        jLabel10TotalL2.setBounds(600, 70, 60, 30);

        jLabel11TotalLucro2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11TotalLucro2.setText("De Compra");
        jPanel1Principal1.add(jLabel11TotalLucro2);
        jLabel11TotalLucro2.setBounds(600, 90, 80, 19);

        jBExcluirF.setBackground(new java.awt.Color(153, 153, 153));
        jBExcluirF.setForeground(new java.awt.Color(0, 0, 0));
        jBExcluirF.setText("Excluir");
        jBExcluirF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirFActionPerformed(evt);
            }
        });
        jPanel1Principal1.add(jBExcluirF);
        jBExcluirF.setBounds(700, 130, 70, 30);

        jLabel5Produtoss2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5Produtoss2.setText("Do Produto");
        jPanel1Principal1.add(jLabel5Produtoss2);
        jLabel5Produtoss2.setBounds(340, 140, 80, 19);

        jLabel1Produtos2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1Produtos2.setText("Codigor");
        jPanel1Principal1.add(jLabel1Produtos2);
        jLabel1Produtos2.setBounds(340, 120, 90, 30);

        txtCdg.setEditable(false);
        txtCdg.setBackground(new java.awt.Color(153, 153, 153));
        txtCdg.setForeground(new java.awt.Color(0, 0, 0));
        txtCdg.setEnabled(false);
        jPanel1Principal1.add(txtCdg);
        txtCdg.setBounds(420, 130, 90, 30);

        jTFornecedor.setBackground(new java.awt.Color(153, 153, 153));
        jTFornecedor.setForeground(new java.awt.Color(0, 0, 0));
        jTFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Cnpj", "Telefone", "Cep", "Codigo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFornecedorMouseClicked(evt);
            }
        });
        jTFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFornecedorKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTFornecedor);

        jPanel1Principal1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 180, 880, 490);

        jBAlterarF.setBackground(new java.awt.Color(153, 153, 153));
        jBAlterarF.setForeground(new java.awt.Color(0, 0, 0));
        jBAlterarF.setText("Alterar");
        jBAlterarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarFActionPerformed(evt);
            }
        });
        jPanel1Principal1.add(jBAlterarF);
        jBAlterarF.setBounds(520, 130, 70, 30);

        jBCadastrarF.setBackground(new java.awt.Color(153, 153, 153));
        jBCadastrarF.setForeground(new java.awt.Color(0, 0, 0));
        jBCadastrarF.setText("Cadastrar");
        jBCadastrarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarFActionPerformed(evt);
            }
        });
        jPanel1Principal1.add(jBCadastrarF);
        jBCadastrarF.setBounds(600, 130, 87, 30);

        jLabel5Produtoss3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5Produtoss3.setText("Do Fornecedor");
        jPanel1Principal1.add(jLabel5Produtoss3);
        jLabel5Produtoss3.setBounds(20, 140, 96, 19);

        jLabel1Produtos3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1Produtos3.setText("Cep");
        jPanel1Principal1.add(jLabel1Produtos3);
        jLabel1Produtos3.setBounds(20, 120, 90, 30);

        txtCep.setBackground(new java.awt.Color(153, 153, 153));
        txtCep.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1Principal1.add(txtCep);
        txtCep.setBounds(120, 130, 210, 30);

        jBAtualizar.setBackground(new java.awt.Color(153, 153, 153));
        jBAtualizar.setForeground(new java.awt.Color(0, 0, 0));
        jBAtualizar.setText("Atualizar");
        jBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarActionPerformed(evt);
            }
        });
        jPanel1Principal1.add(jBAtualizar);
        jBAtualizar.setBounds(780, 130, 80, 30);

        getContentPane().add(jPanel1Principal1);
        jPanel1Principal1.setBounds(0, 0, 880, 674);

        jMenuBar2.setForeground(new java.awt.Color(153, 153, 153));

        jMenu1Opcoes.setText("Opções");

        jMCadastrarFornecedor.setText("Cadastrar Fornecedor");
        jMCadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarFornecedorActionPerformed(evt);
            }
        });
        jMenu1Opcoes.add(jMCadastrarFornecedor);

        jMCadastrarProdutos.setText("Cadastrar Produtos");
        jMCadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarProdutosActionPerformed(evt);
            }
        });
        jMenu1Opcoes.add(jMCadastrarProdutos);

        jMStatus.setText("Entrada de Produtos");
        jMStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMStatusActionPerformed(evt);
            }
        });
        jMenu1Opcoes.add(jMStatus);

        jMSaida.setText("Saida de  Produtos");
        jMSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSaidaActionPerformed(evt);
            }
        });
        jMenu1Opcoes.add(jMSaida);

        jMenu.setText("Menu");
        jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActionPerformed(evt);
            }
        });
        jMenu1Opcoes.add(jMenu);

        jMLogar.setText("Logar");
        jMLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMLogarActionPerformed(evt);
            }
        });
        jMenu1Opcoes.add(jMLogar);

        jMenuBar2.add(jMenu1Opcoes);

        jMenu2Config.setText("Configurações");

        jMenuItem4Ferramentas.setText("Ferramentas");
        jMenu2Config.add(jMenuItem4Ferramentas);

        jMenuBar2.add(jMenu2Config);

        jMenu3Sair.setText("Sair");

        jMenuItem1Sair.setText("Sair");
        jMenu3Sair.add(jMenuItem1Sair);

        jMenuBar2.add(jMenu3Sair);

        setJMenuBar(jMenuBar2);

        setSize(new java.awt.Dimension(896, 733));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBExcluirFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirFActionPerformed
        ExcluirFornecedor();
        listaFornecedor();
    }//GEN-LAST:event_jBExcluirFActionPerformed

    private void jBAlterarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarFActionPerformed
        AlterarFornecedor();
        listaFornecedor();

    }//GEN-LAST:event_jBAlterarFActionPerformed

    private void jBCadastrarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarFActionPerformed
        CadastrarFornecedor();
        listaFornecedor();
    }//GEN-LAST:event_jBCadastrarFActionPerformed

    private void jTFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFornecedorMouseClicked
        // TODO add your handling code here
        CarregarCampos();
    }//GEN-LAST:event_jTFornecedorMouseClicked

    private void jTFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFornecedorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFornecedorKeyReleased

    private void jMCadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarFornecedorActionPerformed
        View objtview = new View();
        objtview.MenuFornecedor();
        dispose();
    }//GEN-LAST:event_jMCadastrarFornecedorActionPerformed

    private void jMStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMStatusActionPerformed
        View objtview = new View();
        objtview.MenuEntrada();
        dispose();
    }//GEN-LAST:event_jMStatusActionPerformed

    private void jMSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSaidaActionPerformed
        View objtview = new View();
        objtview.MenuSaida();
        dispose();
    }//GEN-LAST:event_jMSaidaActionPerformed

    private void jMCadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarProdutosActionPerformed
        View objtview = new View();
        objtview.MenuProdutos();
        dispose();
    }//GEN-LAST:event_jMCadastrarProdutosActionPerformed

    private void jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActionPerformed
        View objtview = new View();
        objtview.Menu();
        dispose();
    }//GEN-LAST:event_jMenuActionPerformed

    private void jMLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMLogarActionPerformed
        View objtview = new View();
        objtview.MenuLogin();
        dispose();
    }//GEN-LAST:event_jMLogarActionPerformed

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed
        AtualizarProduto();
    }//GEN-LAST:event_jBAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterarF;
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBCadastrarF;
    private javax.swing.JButton jBExcluirF;
    private javax.swing.JLabel jLabel10TotalL;
    private javax.swing.JLabel jLabel10TotalL2;
    private javax.swing.JLabel jLabel11TotalLucro;
    private javax.swing.JLabel jLabel11TotalLucro2;
    private javax.swing.JLabel jLabel1Menu;
    private javax.swing.JLabel jLabel1Menu1;
    private javax.swing.JLabel jLabel1Produtos;
    private javax.swing.JLabel jLabel1Produtos1;
    private javax.swing.JLabel jLabel1Produtos2;
    private javax.swing.JLabel jLabel1Produtos3;
    private javax.swing.JLabel jLabel5Produtoss;
    private javax.swing.JLabel jLabel5Produtoss1;
    private javax.swing.JLabel jLabel5Produtoss2;
    private javax.swing.JLabel jLabel5Produtoss3;
    private javax.swing.JLabel jLabel8TotalC;
    private javax.swing.JLabel jLabel8TotalC1;
    private javax.swing.JLabel jLabel9TotalCaptal;
    private javax.swing.JLabel jLabel9TotalCaptal1;
    private javax.swing.JMenuItem jMCadastrarFornecedor;
    private javax.swing.JMenuItem jMCadastrarProdutos;
    private javax.swing.JMenuItem jMLogar;
    private javax.swing.JMenuItem jMSaida;
    private javax.swing.JMenuItem jMStatus;
    private javax.swing.JMenuItem jMenu;
    private javax.swing.JMenu jMenu1Opcoes;
    private javax.swing.JMenu jMenu2Config;
    private javax.swing.JMenu jMenu3Sair;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1Sair;
    private javax.swing.JMenuItem jMenuItem4Ferramentas;
    private javax.swing.JPanel jPanel1Principal;
    private javax.swing.JPanel jPanel1Principal1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTFornecedor;
    private javax.swing.JTextField txtCdg;
    private javax.swing.JTextField txtCep;
    public javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtDescForn;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables

    public MenuFornecedor() {
        initComponents();
        listaFornecedor();

        DefaultTableModel modelo = (DefaultTableModel) jTFornecedor.getModel();
        jTFornecedor.setRowSorter(new TableRowSorter(modelo));
    }

    private void listaFornecedor() {
        try {
            FornecedorDAO objFornecedorDAO = new FornecedorDAO();

            DefaultTableModel model = (DefaultTableModel) jTFornecedor.getModel();//montara a tabela
            model.setNumRows(0);

            ArrayList<Controle.Fornecedor> lista = objFornecedorDAO.pesquisarFornecedor();//pegara os dados do db e passara para tabela

            for (int num = 0; num < lista.size(); num++) {//enquanto tiver linhas capte os dados
                model.addRow(new Object[]{
                    lista.get(num).getDescrForn(),
                    lista.get(num).getCnpj(),
                    lista.get(num).getTel(),
                    lista.get(num).getCep(),
                    lista.get(num).getCodig()
                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, " ERRO Listar Fornecedor" + erro);
        }
    }

    private void CadastrarFornecedor() {
        Fornecedor f = new Fornecedor();
        FornecedorDAO dao = new FornecedorDAO();

        f.setDescrForn(txtDescForn.getText());//capta dado digitado e armazena em variavel jogando para o banco de dados
        f.setCnpj(Integer.parseInt(txtCnpj.getText()));
        f.setTel(Integer.parseInt(txtTel.getText()));
        f.setCep(Integer.parseInt(txtCep.getText()));
        dao.cadastroFornecedor(f);//executa o metodo com comandos do Db

        txtDescForn.setText("");
        txtCnpj.setText("");
        txtTel.setText("");
        txtCep.setText("");
    }
    
    public void AtualizarProduto() {//atualiza a tabela apos alterações..

        DefaultTableModel modelo = (DefaultTableModel) jTFornecedor.getModel();
        modelo.setNumRows(0);
        FornecedorDAO fdao = new FornecedorDAO();//objeto de produtosDAO
        
        for (Controle.Fornecedor objfornecedor : fdao.pesquisarFornecedor()) {
            
            modelo.addRow(new Object[]{
                objfornecedor.getDescrForn(),
                objfornecedor.getCnpj(),
                objfornecedor.getTel(),
                objfornecedor.getCep(),
                objfornecedor.getCodig(),

            });
        }
        LimparCampos();
    }
    
    private void ExcluirFornecedor() {
        Fornecedor f = new Fornecedor();
        FornecedorDAO dao = new FornecedorDAO();

        f.setCodig((int) jTFornecedor.getValueAt(jTFornecedor.getSelectedRow(), 4));
        dao.ExcluirProduto(f);
    }

    private void AlterarFornecedor() {

        Fornecedor f = new Fornecedor();
        FornecedorDAO dao = new FornecedorDAO();

        f.setDescrForn(txtDescForn.getText());
        f.setCnpj(Integer.parseInt(txtCnpj.getText()));
        f.setTel(Integer.parseInt(txtTel.getText()));
        f.setCep(Integer.parseInt(txtCep.getText()));
        f.setCodig((int) jTFornecedor.getValueAt(jTFornecedor.getSelectedRow(), 4));
        dao.AlterarFornecedor(f);

        LimparCampos();

    }
    
    private void CarregarCampos(){
        txtDescForn.setText(jTFornecedor.getValueAt(jTFornecedor.getSelectedRow(), 0).toString());
        txtCnpj.setText(jTFornecedor.getValueAt(jTFornecedor.getSelectedRow(), 1).toString());
        txtTel.setText(jTFornecedor.getValueAt(jTFornecedor.getSelectedRow(), 2).toString());
        txtCep.setText(jTFornecedor.getValueAt(jTFornecedor.getSelectedRow(), 3).toString());
        txtCdg.setText(jTFornecedor.getValueAt(jTFornecedor.getSelectedRow(), 4).toString());
    }
    
    private void LimparCampos(){
        txtDescForn.setText("");
        txtCnpj.setText("");
        txtTel.setText("");
        txtCep.setText("");
        txtCdg.setText("");
    }
    
}
